### PR TITLE
Update dependencies, 1.3.4

### PR DESCRIPTION
**Pull request by antsgar**
- Run ncu to update dependencies
- Made changes to webpack.config. Both extract-js-webpack-plugin and uglifyJsPlugin are now deprecated, replaced by mini-css-webpack-plugin and terser-webpack-plugin respectively
- Added --mode=production to build script, mode is required since Webpack 4
- Babel loader 8 requires Babel 7, updated Babel using babel-upgrade https://github.com/babel/babel-upgrade
- Run build script to generate dist files

### CODE REVIEW

**Comment by mobitar** [comment]
Hmm, any idea why we need so many new babel plugins? Is this for KendoUI? Shouldn't that be already compiled?

**Comment by antsgar** [comment]
Had to update Babel to v7 since Babel Loader 8 requires it and ran babel-upgrade to perform the upgrade automatically. In theory it should have added the plugins that correspond to "stage-0" which has been deprecated, but it does seem like it added more plugins than it needed to. Let me re-check the docs to see which ones are actually equivalent to preset-stage-0

**Comment by antsgar** [comment]
Re-checked docs, the added plugins are actually required if we want to keep the same configuration as with preset-stage-0. Here's the detail of the plugins included in each stage: https://github.com/babel/babel/tree/755ec192e22c6b6e00782e4810366d0166fdbebd/packages/babel-preset-stage-0#babelpreset-stage-0. Stage 0 includes all the other stages as well per https://babeljs.io/blog/2018/07/27/removing-babels-stage-presets. Let me know if that makes sense!

**Comment by mobitar** [comment]
I think the list in their docs is just an exhaustive one we are supposed to pick and choose from. You should remove all of them and only add each one back individually according to how the build process reacts/fails.

**Comment by antsgar** [comment]
But was there a reason for us to have the stage 0 preset before? Because that was basically the same as adding all these plugins, I figured we wanted to keep the same configuration. I can remove them though and see if we need them if we want to take the chance to make things cleaner

**Comment by mobitar** [comment]
I don't recall the specifics tbh. But I'm sure if there was a reason for it, it was only a subset of plugins we needed and not all of them.

**Comment by antsgar** [comment]
That makes sense, let me go through the list and see which ones we actually need.

**Comment by antsgar** [comment]
Updated, plugin-proposal-class-properties was the only plugin causing the build to fail when removed.

**Pull request merged**
