### PR TITLE
Update Kendo UI to 2020.2.513 version

### PR DESCRIPTION
**Pull request by antsgar**
- Generate custom build for the latest version and replace JS file
- Replace styles files for themes currently in use
- Remove files for themes that aren't currently being used

### CODE REVIEW

**Comment by mobitar** [comment]
Looks great overall! Only thing is that there appears to be a new UI element here that is not properly stylized when using some of our themes:

Screen Shot 2020-05-18 at 1 10 44 PM

**Comment by antsgar** [comment]
@mobitar fixed the element you pointed out and also went through all of the components to fix a few other styling issues. SN colors weren't being applied to hover and selected states for options in dropdowns in general (on top of the name editor one, the font, font size, format and sorting dropdowns). Also the text for the primary buttons wasn't visible when hovered, I tried to follow the behavior for buttons in the SN app. Let me know if it looks okay!

**Comment by mobitar** [comment]
Hmm, we seem to be missing a border now for under the toolbar:

Screen Shot 2020-05-21 at 12 20 15 PM

(See how on top of where it says E11 there is no border on top).

In the production version there is a border which helps separate the bars nicely.

Screen Shot 2020-05-21 at 12 21 21 PM

**Comment by antsgar** [comment]
Seems like they removed this border from their theme, I added it to our custom styling. Let me know if you see any other differences

**Pull request merged**
